### ISSUE TITLE
No link to comments

### ISSUE THREAD

**Issue by youridekker** [move4mobile/geekbites#149]
When you create a new post, the link to the comments will not be generated underneath the post title.
See this [preview](https://m4m-geekbites--pr145-feature-web-apis-pos-i2rqoj9y.web.app/)

**Comment by cassshh** [comment]
It does work (now) for me.
Maybe it needs to processing time?
<img width="1680" alt="Screenshot 2021-03-02 at 11 23 50" src="https://user-images.githubusercontent.com/10263056/109634654-c56cc100-7b49-11eb-8f56-54d830014918.png">

**Comment by youridekker** [comment]
Underneath the title, there is no link. 
![afbeelding](https://user-images.githubusercontent.com/38322349/109834818-e06f2c00-7c42-11eb-8fb8-21517c57b6d3.png)
