### ISSUE TITLE
Can I rename this repository to 'geekbites'

### ISSUE THREAD

**Issue by mschilling** [move4mobile/geekbites#23]
Open question: should I rename this repository to `geekbites`?

The current repository name `move4mobile.github.io` was just a convention to get the blog automatically build and deployed to GitHub pages. 

Since we've moved the blog to Firebase, this convention became obsolete..

**Comment by wwolters** [comment]
I was thinking the same. We should remember to update relevant services. What happens to e.g. travis?

**Comment by mschilling** [comment]
We have to update local references in .git folder, and that's probably it. 

Maybe we have to re-enable travis build, but the build configuration itself remains the same. It should automatically work :-)

code heroes: will introduce new repo with new stats .. but that's fine :-)

**Comment by mschilling** [comment]
Step 1 completed: repo renamed to `geekbites`

**Comment by mschilling** [comment]
Completed
