### ISSUE TITLE
Automatic merge for [Dependabot] PR's

### ISSUE THREAD

**Issue by mschilling** [move4mobile/geekbites#69]
Experiment with some tools.

Main requirement: find a way to automise the process auto merging PR's.

**Comment by cassshh** [comment]
@mschilling Should be (easily) possible using Dependabot's config files:
https://dependabot.com/docs/config-file/#automerged_updates

**Comment by mschilling** [comment]
First you have to enable something on the organisation level to make this possible.
Then, Dependabot scares me by saying: 

```
Dependabot can be configured to automatically merge dependency update PRs on a project-by-project basis.

By enabling auto-merging you take full responsibility for any changes that are auto-merged.
```

Therefore will experiment with one or two other solutions first

**Comment by mschilling** [comment]
1) https://github.com/pascalgn/automerge-action
2) https://github.com/ridedott/merge-me-action

**Comment by cassshh** [comment]
```
For all of the options below Dependabot will wait until all your status checks pass before merging.
You can also set working hours for automerging in your dashboard account settings.
```

> ```
> By enabling auto-merging you take full responsibility for any changes that are auto-merged.
> ```

I think this is more towards the idea of;
- All your (GitHub) tests pass
- It will automatically merge the PR
But if the code breaks because of something the isn't tested with your setup GitHub tests, it isn't Dependabot its fault.

**Comment by cassshh** [comment]
> https://github.com/pascalgn/automerge-action
https://github.com/ridedott/merge-me-action

Nonetheless, I do like the idea of a label for merging as well

**Comment by mschilling** [comment]
- dependabot it is
- `automerge-action` is a great alternative for non-dependabot use cases
